In [1]:
import torch
torch.__version__

'2.6.0'

### Tensors

In [4]:
scaler = torch.tensor(3)
scaler

tensor(3)

In [10]:
scaler.ndim

0

In [12]:
scaler.item() # get the python int from scaler

3

In [15]:
vector = torch.tensor([2,3,4])
vector

tensor([2, 3, 4])

In [16]:
print(vector.ndim, vector.shape) # returns 3 because 3 elements where paces inside []

1 torch.Size([3])


In [19]:
vector = torch.tensor([[[2,3,4],
                        [1,1,1],
                        [3,3,3],
                        [4,4,4]]])
vector

tensor([[[2, 3, 4],
         [1, 1, 1],
         [3, 3, 3],
         [4, 4, 4]]])

In [21]:
vector.shape 
###
# 0 = outer array
# 1 = no of elements
# 3 = no if elements in innermost array


torch.Size([1, 4, 3])

In [26]:
#vector  = a 2-dimensional array of numbers
#matrix = n dim array of num
MATRIX =  torch.tensor([[11,22],[11,22],[11,22]])
MATRIX

tensor([[11, 22],
        [11, 22],
        [11, 22]])

In [25]:
MATRIX.shape # col and row

torch.Size([3, 2])

In [30]:
### random tensors

torch.rand(size=(224,224,3)) #image tensor random

tensor([[[0.5144, 0.4548, 0.9302],
         [0.3392, 0.8633, 0.1999],
         [0.9276, 0.9917, 0.9107],
         ...,
         [0.1331, 0.0767, 0.3528],
         [0.3718, 0.5006, 0.7749],
         [0.3111, 0.4472, 0.5971]],

        [[0.8960, 0.9571, 0.5567],
         [0.8087, 0.8386, 0.3021],
         [0.4302, 0.8666, 0.3486],
         ...,
         [0.1869, 0.0300, 0.7954],
         [0.7390, 0.0783, 0.5547],
         [0.1252, 0.3264, 0.9528]],

        [[0.2644, 0.0677, 0.3986],
         [0.9754, 0.0296, 0.3709],
         [0.2845, 0.1869, 0.2744],
         ...,
         [0.3334, 0.5141, 0.5177],
         [0.3406, 0.5589, 0.9212],
         [0.1733, 0.2721, 0.4506]],

        ...,

        [[0.2817, 0.0010, 0.6317],
         [0.2525, 0.3573, 0.8219],
         [0.1436, 0.0642, 0.0162],
         ...,
         [0.9358, 0.4265, 0.7207],
         [0.9082, 0.8337, 0.0866],
         [0.7553, 0.5923, 0.7752]],

        [[0.3683, 0.1834, 0.9447],
         [0.7489, 0.0753, 0.5721],
         [0.

In [31]:
torch.zeros(size=(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
torch.ones(size=(4,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [36]:
zero_like_tensor =  torch.zeros_like(torch.ones(size=(4,5)),dtype=int)
zero_like_tensor

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [37]:
zero_like_tensor.device

device(type='cpu')

#### Manupulating tensors